/**
 * Builds src/bank.ts: curated classic puzzles per difficulty.
 *
 * Every entry is verified to have a unique solution, to be fully solvable by
 * the coach's techniques (no guessing), and to be rated exactly its bucket by
 * `rateDifficulty`. Puzzles are dug from a full grid, removing clues only while
 * the puzzle stays unique and solvable with techniques up to the bucket's
 * hardest one, so the result needs that technique — and nothing harder.
 *
 * Usage:  pnpm --filter @sudoku-2026/core build && node scripts/build-bank.mjs [scale]
 *         (scale multiplies the per-bucket counts; e.g. 0.1 for a quick smoke run)
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { availableParallelism } from "node:os";
import { Worker, isMainThread, parentPort, workerData } from "node:worker_threads";
import { generateSudoku, countSolutions, solvePath, rateDifficulty, createRng } from "../dist/index.mjs";

const BUCKETS = [
  { label: "easy", max: "naked_single", minClues: 36, count: 60 },
  { label: "medium", max: "naked_pair", minClues: 28, count: 60 },
  { label: "hard", max: "box_line_reduction", minClues: 24, count: 60 },
  // X-Wing puzzles are rare (~0.5% of digs); transforms give each one ~10¹² variants.
  { label: "extreme", max: "x_wing", minClues: 22, count: 40 },
];

function shuffled(items, rng) {
  const a = [...items];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

function dig(solution, max, minClues, rng) {
  const grid = solution.split("");
  let clues = 81;
  for (const i of shuffled([...Array(81).keys()], rng)) {
    if (clues <= minClues) break;
    const v = grid[i];
    grid[i] = "0";
    const s = grid.join("");
    if (countSolutions(s) === 1 && solvePath(s, { maxTechnique: max }).solved) clues--;
    else grid[i] = v;
  }
  return grid.join("");
}

if (!isMainThread) {
  // Worker: try seeds k = offset, offset + stride, … and report hits.
  const { label, max, minClues, offset, stride } = workerData;
  for (let k = offset; ; k += stride) {
    const seed = `bank-${label}-${k}`;
    const { solution } = generateSudoku("easy", seed);
    const clues = dig(solution, max, minClues, createRng(`${seed}-dig`));
    if (rateDifficulty(clues).label === label && solvePath(clues).solved) parentPort.postMessage(clues);
  }
} else {
  const scale = Number(process.argv[2] ?? 1);
  const threads = Math.max(1, availableParallelism());
  const bank = {};
  for (const bucket of BUCKETS) {
    const target = Math.max(1, Math.round(bucket.count * scale));
    const t0 = Date.now();
    const found = await new Promise((resolve) => {
      const hits = new Set();
      const workers = Array.from(
        { length: threads },
        (_, offset) => new Worker(new URL(import.meta.url), { workerData: { ...bucket, offset, stride: threads } })
      );
      for (const w of workers) {
        w.on("message", (clues) => {
          hits.add(clues);
          if (hits.size === target) {
            workers.forEach((x) => x.terminate());
            resolve([...hits]);
          }
        });
      }
    });
    bank[bucket.label] = found.sort();
    console.log(`${bucket.label}: ${found.length} puzzles in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
  }

  const out = fileURLToPath(new URL("../src/bank.ts", import.meta.url));
  const body = Object.entries(bank)
    .map(([label, list]) => `  ${label}: [\n${list.map((p) => `    "${p}",`).join("\n")}\n  ],`)
    .join("\n");
  writeFileSync(
    out,
    `// Generated by scripts/build-bank.mjs — do not edit by hand.
// Each entry: unique solution, solvable by the coach without guessing, and
// rated exactly its bucket by rateDifficulty(). Verified in bank.test.ts.

export const PUZZLE_BANK: Record<"easy" | "medium" | "hard" | "extreme", readonly string[]> = {
${body}
};
`
  );
  console.log("wrote", out);
}
